In [1]:
import pandas as pd
import sklearn as tree
from sklearn.model_selection import  train_test_split

In [2]:
datos = pd.read_csv("D:/3.-InteligenciaClase/Dataset/cardio.csv")
datos.head()

,age,gender,chest-pain-type,blood-pressure,cholesterol,Fasting-blood-sugar<120,resting-ecg,maximum-heart-rate,angina,peak,slope,#colored-vessels,thal,class
0,60,Male,Asymptomatic,130,206,False,Hyp,132,True,2.4,Flat,2,Rev,Sick
1,49,Male,AbnormalAngina,130,266,False,Normal,171,False,0.6,Up,0,Normal,Healthy
2,64,Male,Angina,110,211,False,Hyp,144,True,1.8,Flat,0,Normal,Healthy
3,63,Male,Asymptomatic,130,254,False,Hyp,147,False,1.4,Flat,1,Rev,Sick
4,53,Male,Asymptomatic,140,203,True,Hyp,155,True,3.1,Down,0,Rev,Sick

In [3]:
# #!  resting-ecg, maximum-heart-rate, thal, class

datos = datos.drop("age", axis=1)
datos = datos.drop("gender", axis=1)
datos = datos.drop("chest-pain-type", axis=1)
datos = datos.drop("blood-pressure", axis=1)

In [4]:
datos.head()

,cholesterol,Fasting-blood-sugar<120,resting-ecg,maximum-heart-rate,angina,peak,slope,#colored-vessels,thal,class
0,206,False,Hyp,132,True,2.4,Flat,2,Rev,Sick
1,266,False,Normal,171,False,0.6,Up,0,Normal,Healthy
2,211,False,Hyp,144,True,1.8,Flat,0,Normal,Healthy
3,254,False,Hyp,147,False,1.4,Flat,1,Rev,Sick
4,203,True,Hyp,155,True,3.1,Down,0,Rev,Sick

In [7]:
datos["resting-ecg"].value_counts()

resting-ecg
Normal      152
Hyp         147
Abnormal      4
Name: count, dtype: int64